######################################################################
##
## Filename: rgb_threshold.udo
## Created on: Tue Dec 08 03:30:00 PM CST 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
